default['mysql']['server_root_password'] = "password"
default['typo3']['hostname'] = "introductionpackage.dev"
default['typo3']['version'] = "4.6.7"
default['typo3']['dir'] = "/var/www/site"
default['typo3']['db']['database'] = "typo3"
default['typo3']['db']['user'] = "typo3"